# Generated by Django 5.1.6 on 2025-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citizen_password_institute_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$IlqXvHD2MUbLGGZ15HJJqQ$XnUCPdl9Hl6eByTkZdNIVury8wc1fI4S0GES01BBzBw=', max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$K29dKG6hVlIbyBXl2cPX8c$NsKrkimN2kenpbSvJh8esHbGEzaoF5fRW3cbOkYJid4=', max_length=255),
        ),
    ]
