# Generated by Django 5.1.6 on 2025-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_citizen_password_alter_institute_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
